name: garden_ui
description: "Garden Connect UI library"
publish_to: "none"
version: 0.3.4
repository: https://github.com/JardinConnect/GardenUI

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  google_fonts: ^6.2.1
  widgetbook_addon: ^0.0.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.13.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/ui/assets/icons/
